### PR TITLE
Allow annotation/labeling in single cell

### PR DESCRIPTION
**Pull request by rsignell-usgs**
This PR keeps the labeling in a single cell.  Try it on binder at:
https://mybinder.org/v2/gh/rsignell-usgs/EarthAnnotator.git/patch-1

### CODE REVIEW

**Comment by ddbuscombe** [comment]
works great, thanks @rsignell-usgs !

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs , how much work would it be to incorporate this into the cdi classwork?
I'd like to modify the blog-post-I-never-posted and say that now the course can be run completely in Jupyter, and give the binder link...

**Comment by ddbuscombe** [comment]
Not too much work - I just a clear couple of hours. I will try to do it by end of week

**Comment by rsignell-usgs** [comment]
Fantastic!

**Comment by ddbuscombe** [comment]
Stalling out with errors due to a bad conda environment. Bokeh 0.13.0 not playing nicely. I'll keep you posted when I figured it out. Perhaps felipe's pull request may help but I don't understand what he wrote and what that PR does (!)

**Comment by rsignell-usgs** [comment]
Use the packages in the environment.yml in the binder folder. You need that holoviews from pyviz to pull the bokeh 1.0 prerelease

-Rich

**Comment by ddbuscombe** [comment]
The environment.yml installs bokeh 0.13.0. I get the error:

```
WARNING:root:main: FreehandDraw requires bokeh >= 0.13.0
WARNING:root:PathPlot01171: Plotting hook <function set_active_tool at 0x0000021CF3023378> could not be applied:

 list index out of range
```

so I'm going to revert back to what I had originally, which I think is what you're saying:

```
pyviz/label/earthsim::bokeh=1.0.0dev5
```

?

**Comment by ddbuscombe** [comment]
Yep, adding this to the enironment.yml file fixes it for me:

```
pyviz/label/earthsim::bokeh=1.0.0dev5
```

**Comment by rsignell-usgs** [comment]
I meant these lines: https://github.com/dbuscombe-usgs/EarthAnnotator/blob/master/binder/environment.yml#L6-L7
which ends up pulling that `bokeh=1.0.0dev5` package, but I guess it is even better to specify it explicitly!

Supposedly bokeh 1.0 will be released this coming week and hopefully we won't have to do this anymore and just pull from conda-forge.

**Comment by ddbuscombe** [comment]
I'm stalling out again. On one machine I can install the conda environment but the holoviews figure takes too long to render, and eventually runs out of memory and crashes. On another machine I can't install the exact same conda env at all. Perhaps I should just wait until the bokeh 1.0 release?

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs, I just cloned https://github.com/dbuscombe-usgs/cdi_dl_workshop on  pangeo.esipfed.org and it worked fine.   

The environment I use for pangeo.esipfed.org is created here: 
https://github.com/rsignell-usgs/helm-chart/blob/esipfed/docker-images/notebook/Dockerfile

You are trying to build a local environment to run the workshop with this:
https://github.com/dbuscombe-usgs/cdi_dl_workshop/blob/master/binder/environment.yml
Right?

**Comment by ddbuscombe** [comment]
@rsignell-usgs  There is something glitchy about the  ```EarthAnnotate``` class but I can't troubleshoot it because my browser/kernel crashes every time I run it. On a cloud or a local server.

I just cloned https://github.com/dbuscombe-usgs/cdi_dl_workshop on pangeo.esipfed.org and when it executes the cell that contains your ```EarthAnnotate``` class, it thinks about it for about 5 minutes or even more, then either the web browser crashes and the kernel dies immediately, or it will crash at some point during the annotation process.

And yes, I am also verifying that the conda environment installs on my local machines with https://github.com/dbuscombe-usgs/cdi_dl_workshop/blob/master/binder/environment.yml. The exact same happens on my local machine. I can't seem to get past it.

**Comment by ddbuscombe** [comment]
@rsignell-usgs I added the remaining bits of code to the labeling notebook and pushed to https://github.com/dbuscombe-usgs/cdi_dl_workshop.  

Note that I can't test it because of the issues I described before, but all the elements are now in place so the whole workflow can be run on the pangeo server.

I'm in the field next week, then most definitely moving on to something else. I'll check back when bokeh release 1.0

**Comment by rsignell-usgs** [comment]
I ran with no issues. Are you using chrome?

-Rich

**Comment by ddbuscombe** [comment]
Yes, chrome

**Comment by rsignell-usgs** [comment]
I just did recloned your workshop repo https://github.com/dbuscombe-usgs/cdi_dl_workshop on pangeo.esipfed.org and the image annotation worked fine.     I tried on both Chrome and Opera on my windows machine with 16GB RAM (although Opera only used about 2GB RAM to run the notebook)

This is bizarre.   Can you go to pangeo.esipfed.org, click on "control panel" and then click "Stop My Server", wait for screen to refresh ,and then click "My Server"?

**Comment by ddbuscombe** [comment]
Restarted, still fails in the same way. Actually this time I also get new errors with all the ipython widgets that now do not render

**Comment by rsignell-usgs** [comment]
@ocefpaf, can you think of what might explain the different experiences Dan and I are getting, both running the same environment on pangeo.esipfed.org?    

1. login to pangeo.esipfed.org
2. `git clone https://github.com/dbuscombe-usgs/cdi_dl_workshop.git`
3. try running the notebook `cdi_dl_workshop/Day2/2.2.Labeling_images.ipynb

Instead of using the filepicker widget to pick an image file, use this code:
```
import requests
from io import BytesIO
url = 'https://s3.amazonaws.com/esipfed/testing/NewRiver_worldImageryRGB_20m.tif'
response = requests.get(url)
imfile = BytesIO(response.content)
```
The image annotation worked fine for me, but is giving Dan problems.

**Comment by ocefpaf** [comment]
@dbuscombe-usgs and @rsignell-usgs I'm not sure what/how I'm supposed to draw but the code worked just fine and I reached `6. Write result to figure`. There the notebooks failed b/c `colors` is list but the command,

```python
cmap = colors.ListedColormap(colors) 
```

seems to be expecting a `matplotlib` object.

**Comment by rsignell-usgs** [comment]
I just had a colleague here at USGS try the whole workflow and the annotation worked fine.  We hit the same issue in Section 6 that Filipe did, but that's past the part that was problematic for Dan.   @filipe, you can display the image by adding these lines at the end of Section 5:
```
plt.figure(figsize=(10,10))
plt.imshow(im)
plt.imshow(out, alpha=0.5);
``` 

@dbuscombe-usgs,  are you using the base environment on pangeo.esipfed.org or are you using some custom environment  to run the notebook?

That's the only thing left I can think of to explain why you are having problems and other users are not.

**Comment by ddbuscombe** [comment]
Well, today the ipywidgets work for me for file selection and (they didn't yesterday), but the cell containing ```class EarthAnnotate``` still executes/hangs for 5+ minutes before crashing the kernel. It's like it has no graphics memory: while that cell is executing, I can't select other page elements. It's actually worse today than the last few days because the annotation widget never actually renders at all before the kernel crashes 

I've tried using the ```conda::env conda``` kernel (which for me is selected by default) and the "default" kernel - I get the same behavior. 

I'm sorry, I can't look into this any further for at least a week (I'm on fieldwork). I did fix and commit the fix to the ```matplotlib``` object

**Comment by ddbuscombe** [comment]
I have also stopped and restarted my server several times over the last few days but with no noticeable improvement

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs one last request.  Please open a terminal on pangeo.esipfed.org and do:
`conda list` and `conda info --all` and send or gist me the results.

**Pull request merged**
